app:
    resource: '@AppBundle/Controller/'
    type: annotation
    prefix: /admin

_symfonian_indonesia:
    resource: '@SymfonianIndonesiaAdminBundle/Resources/config/routing.yml'
    prefix: /admin