app:
    resource: '@AppBundle/Controller/'
    type: annotation
    prefix: /admin

front:
    resource: '@AppBundle/Front/'
    type: annotation
    prefix: /

_symfonian_indonesia:
    resource: '@SymfonianIndonesiaAdminBundle/Resources/config/routing.yml'
    prefix: /admin