app:
    resource: '@AppBundle/Controller/'
    type: symfonyid
    prefix: /admin

front:
    resource: '@AppBundle/Front/'
    type: annotation
    prefix: /

_symfonian_indonesia:
    resource: '@SymfonyIdAdminBundle/Resources/config/routing.xml'
    prefix: /admin