assetic:
    bundles: ['AppBundle', 'SymfonianIndonesiaAdminBundle']
    node: /usr/bin/nodejs #change to your path
    filters:
        cssrewrite: ~
        uglifyjs2:
            bin: /usr/local/bin/uglifyjs #change to your path
        uglifycss:
            bin: /usr/local/bin/uglifycss #change to your path

framework:
    translator: { fallbacks: ["%locale%"] }

knp_paginator:
    page_range: 5
    default_options:
        page_name: page
        sort_field_name: sort
        sort_direction_name: direction
        distinct: true

knp_menu:
    twig:
        template: knp_menu.html.twig
    templating: false
    default_renderer: twig

symfonyid_core:
    micro_cache:
        cache_lifetime: 5

symfonyid_admin:
    app_title: 'SIAB Skeleton'
    per_page: 10
    identifier: 'id'
    date_time_format: 'd-m-Y' #php date time format
    menu: app_main_menu
    profile_fields: ['username', 'email', 'roles']
    filter: ['name']
    translation_domain: 'SymfonianIndonesiaAdminBundle'
    security:
        user:
            form_class: symfonian_id.admin.user_form
            entity_class: AppBundle\Entity\User
    grid_action:
        show: true
        edit: true
        delete: true
    themes:
        dashboard: 'SymfonianIndonesiaAdminBundle:Index:index.html.twig'
        form_theme: 'SymfonianIndonesiaAdminBundle:Form:fields.html.twig'
        pagination: 'SymfonianIndonesiaAdminBundle:Layout:pagination.html.twig'

fos_user:
    db_driver: orm
    firewall_name: main
    user_class: AppBundle\Entity\User