services:
    app.menu:
        class: AppBundle\Menu\Builder
        arguments:
            - '@router'
            - '@service_container'

    app.main_menu:
        class: Knp\Menu\MenuItem
        factory:
            - '@app.menu'
            - mainMenu
        arguments:
            - '@knp_menu.factory'
            - []
        tags:
            - { name: knp_menu.menu, alias: app_main_menu }

    app.listener.filter_result_listener:
        class: AppBundle\EventListener\FilterTransaksiResult
        tags:
            - { name: kernel.event_listener, event: kernel.controller, method: onKernelController }
            - { name: kernel.event_listener, event: siab.filter_query, method: onFilterQuery }
